server:
  port: 8080
  tomcat:
    connection-timeout: 500000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mywork?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 'a1098644727'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/head/,classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
logging:
  level:
    root: info
  file:
    name: E:\\idea-project\\mywork.log
    max-history:
  pattern:
    rolling-file-name: E:\\idea-project\\mywork-%d{yyyy-MM-dd}.log
myredis:
  database: 0
  password:
  timeout: 1800000
  single:
    address1: localhost:6379
    address2: localhost:6380
  pool:
    size: 20
    connection-timeout: 10000
